///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JGA_MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JGA_MyTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0cabbdbf-a8f7-43f3-8254-9d0a4af36bae")]
    public partial class JGA_MyTest1Repository : RepoGenBaseFolder
    {
        static JGA_MyTest1Repository instance = new JGA_MyTest1Repository();

        /// <summary>
        /// Gets the singleton class instance representing the JGA_MyTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("0cabbdbf-a8f7-43f3-8254-9d0a4af36bae")]
        public static JGA_MyTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JGA_MyTest1Repository() 
            : base("JGA_MyTest1Repository", "/", null, 0, false, "0cabbdbf-a8f7-43f3-8254-9d0a4af36bae", ".\\RepositoryImages\\JGA_MyTest1Repository0cabbdbf.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0cabbdbf-a8f7-43f3-8254-9d0a4af36bae")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class JGA_MyTest1RepositoryFolders
    {
    }
#pragma warning restore 0436
}
